[artf63643,artf63323,artf63396,artf63726]
Make sure that we also instantiate CollabNetApp before sending off to the Remote*Uploaders.  This seems like a likely cause of stacktraces that complains of "NoClassDefFoundError: javax/xml/soap/SOAPException", since this exception is occuring during instantiation of the CollabNetApp soap stub.