artf418282: Jenkins plugin broke in Jenkins v2.266
Issue:
In v2.266, Acegi security is replaced with spring  security hence
ClassNotFoundException: hudson.util.spring.BeanBuilder is thrown
from the CreateFilter function of CollabnetSecurityRealm while
configuring Collabnet security realm.

Fix:
* CollabnetSecurityRealm.java
  (createFilter): Remove this method in favor of the default create filter function